name: HFUTSCNetworkStudy

on:
  watch:
    types: [started]           # 仓库被 star 时触发
  schedule:
    - cron: "0 22 * * *"       # 每天 22:00 定时触发

jobs:
  checkin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run checkin
        id: run_checkin
        run: |
          python3 checkin.py --key_session=${{ secrets.KEY_SESSION }} --secret=${{ secrets.SECRET }} --page_max=${{ secrets.PAGE_MAX }}
          exit 1
        continue-on-error: true
      
      - name: Send ServerChan notification if failed
        if: steps.run_checkin.outcome == 'failure'
        uses: yakumioto/serverchan-action@v2
        with:
          key: ${{ SCT300725TtIk8EnKAmGGhutD5rwK6nGYs }}
          text: "[HFUTSCNetworkStudy] ❌ Checkin Job Failed"
          desp: |
            仓库: ${{ github.repository }}
            运行号: ${{ github.run_number }}
            查看详情: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
