name: HFUTSCNetworkStudy

on:
  schedule:
    - cron: "0 22 * * *"   # 每天22:00运行
  watch:
    types: [ started ]

jobs:
  checkin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run checkin
        id: run_checkin
        run: |
          python3 checkin.py --key_session=${{ secrets.KEY_SESSION }} --secret=${{ secrets.SECRET }} --page_max=${{ secrets.PAGE_MAX }}
          # 模拟失败，用于测试 Server酱通知
          exit 1

      - name: Send Server酱 notification if failed
        if: ${{ failure() }}
        run: |
          curl -s "https://sctapi.ftqq.com/SCT300725TtIk8EnKAmGGhutD5rwK6nGYs.send?title=[HFUTSCNetworkStudy]%20❌%20Checkin%20Job%20Failed&desp=仓库:%20${{ github.repository }}%0A运行号:%20${{ github.run_number }}%0A查看详情:%20${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" || true
