name: HFUTSCNetworkStudy

on:
  schedule:
    - cron: "0 22 * * *"
  workflow_dispatch: # 支持手动触发
  watch:
    types: [started]

permissions:
  contents: read # 权限配置，GitHub Actions 无需设置 secrets 权限

jobs:
  checkin:
    runs-on: ubuntu-latest
    steps:
      - name: Debug ENABLED value
        run: echo "ENABLED=${{ secrets.ENABLED }}"
        shell: bash
      - name: Check if enabled
        run: |
          if [ "${{ secrets.ENABLED }}" != "true" ]; then
            echo "Workflow is paused. Exiting..."
            exit 0
          fi
        shell: /usr/bin/bash
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run checkin
        run: |
          python3 checkin.py --key_session=${{ secrets.KEY_SESSION }} --secret=${{ secrets.SECRET }} --page_max=${{ secrets.PAGE_MAX }}
      - name: Keep alive
        uses: gautamkrishnar/keepalive-workflow@v1
